# Generated by Django 3.2.3 on 2021-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='profile_url',
            field=models.URLField(max_length=2000),
        ),
    ]
